services:

  postgres:
    image: postgres:16-alpine
    container_name: opsmind_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres_default
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/01-init-databases.sql:ro
      - ./init-auth-schema.sql:/docker-entrypoint-initdb.d/02-init-auth-schema.sql:ro
      - ./init-project-schema.sql:/docker-entrypoint-initdb.d/03-init-project-schema.sql:ro

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    depends_on:
      - auth-service
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000/
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    restart: unless-stopped
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/opsmind_auth
      - PORT=8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    restart: unless-stopped

  project-service:
    build:
      context: ./services/project-service
      dockerfile: Dockerfile
    depends_on:
      - auth-service
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/opsmind_project
      - PORT=8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    restart: unless-stopped

volumes:
  postgres_data:
